### ISSUE TITLE
Please explain plugin usefulness

### ISSUE THREAD

**Issue by pcav** [demarcog/Coordtransform#1]
From the description in the About it is not clear how the plugin extends core functionalities.
Thanks.

**Comment by demarcog** [comment]
This plugin let the user take advantage of QgsCoordinateReferenceSystem Class functionalities and allows the user to have a conversion software like CartLab inside Qgis. It is very useful when dealing with georeferencing tasks to check one point coordinates in a different CRS or simply when the user would like to know a point's coordinates in a different CRS. 
Thank you

**Comment by pcav** [comment]
Please add a note about this in the About.
I think more or less the same functionality is present in the custom CS dialog, but I can understand your plugin make it more usable.
Thanks.

**Comment by demarcog** [comment]
I will do that and I'll upload the plugin again. As far as I can remember  the custom CS dialog only permits a one way conversion from geographic/wgs84 to custom CRS coordinate conversion while this plugin let the user convert coordinates from whatever to whatever CRS. Maybe I should add this in the about too?
Thank you

**Comment by pcav** [comment]
Agreed.
Thanks.

**Comment by demarcog** [comment]
I've just uploaded the updated metadata.txt  plugin version!
